
import { useState } from 'react';
import React from 'react';
import { generateProductVisual, editProductImage } from '../geminiService';

interface ImageGeneratorProps {
  productName: string;
  description?: string;
  onImageGenerated?: (url: string) => void;
  initialImageUrl?: string;
}

const ImageGenerator: React.FC<ImageGeneratorProps> = ({ productName, onImageGenerated, initialImageUrl }) => {
  const [imageUrl, setImageUrl] = useState<string | null>(initialImageUrl || null);
  const [loading, setLoading] = useState(false);
  const [editPrompt, setEditPrompt] = useState('');
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    setLoading(true);
    setError(null);
    try {
      const url = await generateProductVisual(productName);
      setImageUrl(url);
      if (onImageGenerated) onImageGenerated(url);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  const handleEdit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!imageUrl || !editPrompt) return;
    setLoading(true);
    try {
      const url = await editProductImage(imageUrl, editPrompt);
      setImageUrl(url);
      setEditPrompt('');
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="bg-white rounded-[2.5rem] p-8 border border-slate-200 shadow-xl mt-8">
      <div className="flex justify-between items-center mb-6">
        <h3 className="font-black text-xl flex items-center gap-2">
          <div className="bg-purple-100 p-2 rounded-xl text-purple-600">🎨</div>
          AI Ad Visual Artist
        </h3>
        {imageUrl && <button onClick={handleGenerate} className="text-[10px] font-black text-purple-600 uppercase hover:underline">Regenerate New</button>}
      </div>

      {!imageUrl && !loading && (
        <button onClick={handleGenerate} className="w-full py-16 border-4 border-dashed rounded-[2rem] hover:bg-purple-50 flex flex-col items-center gap-3 transition-all border-slate-100 group">
          <span className="text-4xl group-hover:scale-110 transition-transform">📷</span>
          <span className="font-black text-slate-400 uppercase text-xs">Create Product Visual</span>
        </button>
      )}

      {loading && (
        <div className="py-20 text-center animate-pulse">
          <div className="w-10 h-10 border-4 border-purple-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="font-black text-slate-900">AI Artist is painting...</p>
        </div>
      )}

      {imageUrl && !loading && (
        <div className="space-y-6">
          <div className="relative rounded-[2rem] overflow-hidden border-4 border-white shadow-2xl group">
            <img src={imageUrl} className="w-full h-auto transition-transform duration-700 group-hover:scale-105" alt="AI Generated" />
            <div className="absolute inset-x-0 bottom-0 p-6 bg-gradient-to-t from-black/80 to-transparent">
              <h4 className="text-white font-black text-lg">{productName}</h4>
              <p className="text-[10px] text-white/60 font-bold uppercase tracking-widest mt-1">Ready for Facebook Ad</p>
            </div>
            {/* Watermark/Footer */}
            <div className="absolute bottom-3 right-4 text-[8px] text-white/30 font-bold uppercase tracking-widest pointer-events-none drop-shadow-sm">
              AI-generated by ဈေးသည်
            </div>
          </div>
          <form onSubmit={handleEdit} className="flex gap-2">
            <input 
              value={editPrompt} 
              onChange={(e) => setEditPrompt(e.target.value)} 
              placeholder="ပုံစံပြောင်းလိုလျှင် ရေးပေးပါ (ဥပမာ- သစ်သားစားပွဲပေါ်တင်ပေးပါ)" 
              className="flex-1 px-5 py-3.5 rounded-2xl border bg-slate-50 text-sm font-bold outline-none focus:bg-white focus:border-purple-400 transition-all shadow-inner" 
            />
            <button className="bg-slate-900 text-white px-8 rounded-2xl font-black text-xs active:scale-95 shadow-lg">EDIT</button>
          </form>
        </div>
      )}

      {error && <div className="mt-4 text-xs text-red-500 font-bold text-center">⚠️ {error}</div>}
    </div>
  );
};

export default ImageGenerator;
